import * as React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

interface LineItem { desc: string; qty: number; unit_price: number; amount?: number; }
interface Props {
  company: { name: string; abn?: string; address?: string; logoUrl?: string };
  invoice: { invoice_number: string; created_at: string; due_at?: string; line_items: LineItem[]; subtotal: number; tax: number; total: number };
  customer: { name: string; address: string };
}

const styles = StyleSheet.create({
  page: { padding: 32, fontFamily: 'Helvetica', color: '#0F172A' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  h1: { fontSize: 20, fontWeight: 700 },
  meta: { fontSize: 10, color: '#64748B' },
  tableHead: { flexDirection: 'row', backgroundColor: '#F1F5F9', padding: 8, borderRadius: 6, marginTop: 16 },
  th: { fontSize: 9, fontWeight: 700, flex: 1 },
  row: { flexDirection: 'row', padding: 8, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  td: { fontSize: 10, flex: 1 },
  totals: { marginTop: 16, alignItems: 'flex-end', gap: 4 },
  totalLine: { flexDirection: 'row', gap: 16 },
  totalLabel: { fontSize: 10, color: '#64748B' },
  totalValue: { fontSize: 11, fontWeight: 700, minWidth: 80, textAlign: 'right' as const },
  footer: { marginTop: 32, fontSize: 9, color: '#94A3B8', textAlign: 'center' as const },
});

export function InvoicePdf({ company, invoice, customer }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.h1}>{company.name}</Text>
            {company.abn ? <Text style={styles.meta}>ABN {company.abn}</Text> : null}
            {company.address ? <Text style={styles.meta}>{company.address}</Text> : null}
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={styles.h1}>TAX INVOICE</Text>
            <Text style={styles.meta}>{invoice.invoice_number}</Text>
            <Text style={styles.meta}>{new Date(invoice.created_at).toLocaleDateString()}</Text>
          </View>
        </View>

        <View>
          <Text style={{ fontSize: 10, fontWeight: 700 }}>Bill To</Text>
          <Text style={{ fontSize: 11 }}>{customer.name}</Text>
          <Text style={styles.meta}>{customer.address}</Text>
        </View>

        <View style={styles.tableHead}>
          <Text style={styles.th}>Description</Text>
          <Text style={[styles.th, { flex: 0.3, textAlign: 'right' as const }]}>Qty</Text>
          <Text style={[styles.th, { flex: 0.4, textAlign: 'right' as const }]}>Price</Text>
          <Text style={[styles.th, { flex: 0.4, textAlign: 'right' as const }]}>Amount</Text>
        </View>
        {invoice.line_items.map((li, i) => (
          <View key={i} style={styles.row}>
            <Text style={styles.td}>{li.desc}</Text>
            <Text style={[styles.td, { flex: 0.3, textAlign: 'right' as const }]}>{li.qty}</Text>
            <Text style={[styles.td, { flex: 0.4, textAlign: 'right' as const }]}>${li.unit_price.toFixed(2)}</Text>
            <Text style={[styles.td, { flex: 0.4, textAlign: 'right' as const }]}>${((li.amount ?? li.qty * li.unit_price)).toFixed(2)}</Text>
          </View>
        ))}

        <View style={styles.totals}>
          <View style={styles.totalLine}><Text style={styles.totalLabel}>Subtotal</Text><Text style={styles.totalValue}>${invoice.subtotal.toFixed(2)}</Text></View>
          <View style={styles.totalLine}><Text style={styles.totalLabel}>GST</Text><Text style={styles.totalValue}>${invoice.tax.toFixed(2)}</Text></View>
          <View style={styles.totalLine}><Text style={[styles.totalLabel, { fontWeight: 700, color: '#0F172A' }]}>Total</Text><Text style={[styles.totalValue, { fontSize: 13 }]}>${invoice.total.toFixed(2)}</Text></View>
        </View>

        <Text style={styles.footer}>Generated by FieldOps — Pay instantly via the payment link on your invoice.</Text>
      </Page>
    </Document>
  );
}
