/**
 * Minimal, dependency-free PDF writer for invoices.
 *
 * Pure ASCII output (uncompressed Helvetica, base-14 font), so the file can
 * be written with a UTF-8 string — no Buffer, no pdfkit, no @react-pdf in
 * the bundle (those never resolved under Metro for native and broke iOS /
 * Android builds). Every byte of the output is in 0x20–0x7E, so string
 * offsets are also byte offsets, which keeps the xref table exact.
 */

export interface PdfLineItem {
  desc: string;
  qty: number;
  unit_price: number;
  amount: number;
}

export interface InvoicePdfData {
  invoiceNumber: string;
  createdAt: string; // ISO timestamp
  companyName: string;
  abn?: string;
  customerName: string;
  customerAddress: string;
  lineItems: PdfLineItem[];
  subtotal: number;
  tax: number;
  total: number;
}

const PAGE_W = 595; // A4 portrait, points
const PAGE_H = 842;
const MARGIN = 50;
const BOTTOM = 60;
const LINE_H = 14;

/** ASCII-safe + PDF string escapes. Non-ASCII becomes '?'. */
function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/[^\x20-\x7E]/g, '?')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function money(n: number): string {
  return `$${(Number.isFinite(n) ? n : 0).toFixed(2)}`;
}

/** Approximate Helvetica text width (avg 0.5em) for right-alignment. */
function approxWidth(s: string, size: number): number {
  return s.length * size * 0.5;
}

function truncate(s: string, max: number): string {
  const str = String(s ?? '');
  return str.length <= max ? str : `${str.slice(0, max - 1)}…`.replace(/…/g, '...');
}

export function buildInvoicePdf(d: InvoicePdfData): string {
  const pages: string[][] = [];
  let ops: string[] = [];
  let y = PAGE_H - MARGIN;

  const text = (x: number, yy: number, str: string, size = 10, bold = false) => {
    ops.push(`BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${yy} Td (${esc(str)}) Tj ET`);
  };
  const right = (str: string, size: number, bold = false) => {
    text(PAGE_W - MARGIN - approxWidth(str, size), y, str, size, bold);
  };
  const newPage = () => {
    if (ops.length) pages.push(ops);
    ops = [];
    y = PAGE_H - MARGIN;
  };
  const ensure = (h: number) => {
    if (y - h < BOTTOM) newPage();
  };
  const down = (dy = LINE_H) => {
    y -= dy;
  };

  // ── Header (page 1) ──
  text(MARGIN, y, d.companyName, 18, true);
  down(20);
  if (d.abn) {
    text(MARGIN, y, `ABN ${d.abn}`, 9);
    down(16);
  }
  const savedY = y;
  right(`Invoice ${d.invoiceNumber}`, 14, true);
  down(16);
  right(`Date ${String(d.createdAt ?? '').slice(0, 10)}`, 10);
  y = savedY - 30;

  text(MARGIN, y, 'Bill to', 8, true);
  down(12);
  text(MARGIN, y, d.customerName, 11, true);
  down(13);
  text(MARGIN, y, truncate(d.customerAddress, 70), 10);
  down(24);

  // ── Line items ──
  const COL_DESC = MARGIN;
  const COL_QTY = 350;
  const COL_UNIT = 410;
  const COL_AMT = PAGE_W - MARGIN; // right edge

  const row = (desc: string, qty: string, unit: string, amt: string, bold = false) => {
    ensure(LINE_H + 4);
    text(COL_DESC, y, desc, 9.5, bold);
    text(COL_QTY, y, qty, 9.5, bold);
    text(COL_UNIT, y, unit, 9.5, bold);
    const w = approxWidth(amt, 9.5);
    text(COL_AMT - w, y, amt, 9.5, bold);
    down(LINE_H);
  };

  row('Description', 'Qty', 'Unit price', 'Amount', true);
  y -= 2;
  ops.push(`${MARGIN} ${y} m ${COL_AMT} ${y} l S`);
  down(14);

  for (const li of d.lineItems) {
    row(truncate(li.desc, 45), String(li.qty ?? 1), money(li.unit_price), money(li.amount));
  }

  y -= 6;
  ops.push(`${MARGIN} ${y} m ${COL_AMT} ${y} l S`);
  down(18);

  ensure(60);
  row('', '', 'Subtotal', money(d.subtotal));
  row('', '', 'Tax', money(d.tax));
  row('', '', 'Total', money(d.total), true);

  down(24);
  ensure(30);
  text(MARGIN, y, 'Generated by FieldOps — payment terms: on receipt', 8);
  down(14);
  text(MARGIN, y, `Thank you for your business.`, 9, true);

  if (ops.length) pages.push(ops);

  // ── Page footers ──
  pages.forEach((p, i) => {
    p.push(`BT /F1 8 Tf ${PAGE_W / 2 - 40} 30 Td (${esc(`Page ${i + 1} of ${pages.length}`)}) Tj ET`);
  });

  // ── Assemble objects ──
  // 1 catalog, 2 pages, then (page,content) pairs, then F1, F2
  const fontBase = 3 + pages.length * 2;
  const objects: string[] = [];
  const push = (body: string) => objects.push(body); // index+1 = object id

  push(`<< /Type /Catalog /Pages 2 0 R >>`);
  const kids = pages.map((_, i) => `${3 + i * 2} 0 R`).join(' ');
  push(`<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>`);
  pages.forEach((p, i) => {
    const pageId = 3 + i * 2;
    const contentId = pageId + 1;
    push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 ${fontBase} 0 R /F2 ${fontBase + 1} 0 R >> >> /Contents ${contentId} 0 R >>`
    );
    const stream = p.join('\n');
    push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  });
  push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`);
  push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`);

  // ── xref ──
  let out = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefStart = out.length;
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    out += `${String(off).padStart(10, '0')} 00000 n \n`;
  }
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  return out;
}
